@startuml usecase_diagram.puml
skinparam actorStyle awesome
left to right direction
skinparam packageStyle rectangle
actor Operator as "Оператор"
actor Engineer as "Инженер"
actor Admin as "Администратор"

rectangle "Приложение распознавания давления" {

  ' ---- Общий вход ----
  Operator --> (Вход в систему)
  Engineer --> (Вход в систему)
  Admin --> (Вход в систему)

  (Вход в систему) --> (Выбор роли пользователя)
  (Выбор роли пользователя) --> (Ввод логина и пароля)

  ' ---- Оператор ----
  
  Operator --> (Настройка приложения)

  (Настройка приложения) --> (Выбор последовательности фиксации)
  (Выбор последовательности фиксации) --> (2. Линия)
  (Выбор последовательности фиксации) --> (1. Буфер)
  (Выбор последовательности фиксации) --> (3. Затруб)

  (Настройка приложения) --> (Выбор типа эксплуатации)

  (Выбор типа эксплуатации) --> (Фонтан / УЭЦН)
  (Фонтан / УЭЦН) --> (3 позиции манометра: буфер, линия, затруб)

  (Выбор типа эксплуатации) --> (УШГН / УШВН)
  (УШГН / УШВН) --> (2 позиции манометра: линия, затруб)

  (Настройка приложения) --> (Выбор месторождения)

  Operator --> (Подготовка к фиксации)
  (Подготовка к фиксации) --> (Ввод номера скважины)
  (Подготовка к фиксации) --> (Выбор типа фиксации)

  (Выбор типа фиксации) --> (Фотофиксация)
  (Выбор типа фиксации) --> (Видеофиксация)

  Operator --> (Фиксация давления)
  (Фиксация давления) --> (Распознавание давления)
  (Распознавание давления) --> (Отображение результата: № скважины, давления, сообщение о результате/ошибке)


  ' ---- Инженер ----
  Engineer --> (Просмотр/анализ результатов)
  Engineer --> (Просмотр истории скважин)
  Engineer --> (Экспорт данных)

  ' ---- Администратор ----
  Admin --> (Управление пользователями)
  Admin --> (Настройка справочников)
  Admin --> (Мониторинг системы)
  Admin --> (Просмотр логов)
}

@enduml
